GET http://localhost:4000/users

###

POST http://localhost:4000/users/signup
Content-Type: application/json

{
    "username" : "Aymen",
    "email" : "Aymen27k@gmail.com",
    "password" : "myPassword"
}

###

POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email" : "psicomk@gmail.com",
    "password" : "myPassword"
}

###

GET http://localhost:3000/todos?userId=67963fea34be97aaec5b70ea
authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzkxOTUzMTcsImV4cCI6MTczOTE5NjIxN30.aUPbwiV8ePbdvBIGtun2up-hNvCn7DfpcEF-W_NPSq4

###

GET http://localhost:5173/users/67963fea34be97aaec5b70ea/refresh_token


###
POST http://localhost:4000/users/refresh_token
Content-Type: application/json

{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzkxOTUzMTcsImV4cCI6MTczOTE5NjIxN30.aUPbwiV8ePbdvBIGtun2up-hNvCn7DfpcEF-W_NPSq4"}

###
POST http://localhost:4000/users/logout
authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzkxMDc4ODksImV4cCI6MTczOTEwNzk0OX0.8Lz4ZRWXit4OO1yhrgvVlvpYK_icpvQCKfPQRmO7WYo

###

POST http://localhost:4000/users/forgot-password
Content-Type: application/json

{
  "email": "Aymen27k@gmail.com"
}